### ISSUE TITLE
No dll

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [NotEnoughMadness/NEMLegacy#1]
I just can't find the dll, and i imagine this is just me being a fucking moron but still

**Comment by ExDefault** [comment]
Nem is not updated for the new mpn versions yet.
If you want to use it you have to downgrade your mpn version (theres some steam guides for that but ive never done that) and install nem the old way.

The instructions in readme.md are for an unreleased nem version not ready for use yet
